# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Colorblind Goggles' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'GPUImage'
  # Pods for Colorblind Goggles
  pod 'MultiSelectSegmentedControl'
  pod 'SnapKit'
  pod 'Alamofire'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'Reveal-SDK', '19',  :configurations => ['Debug']

end
